.\" Copyright Oryx Mail Systems GmbH. Enquiries to info@oryx.com, please.
.TH deliver 8 2006-09-24 www.oryx.com "Archiveopteryx Documentation"
.SH NAME
deliver - deliver mail into Archiveopteryx.
.SH SYNOPSIS
.B $BINDIR/deliver [-f sender] destination [filename]
.SH DESCRIPTION
.nh
.PP
The
.B deliver
program injects a single mail message in RFC-822 format into Oryx
Archiveopteryx.
.PP
It connects to Archiveopteryx's LMTP server and delivers the message
there.
.B deliver
is meant as a compatibility shim for use with e.g.
.BR formail (1)
and with MTAs that want to deliver to a program.
.PP
Note that you will generally get better performance by using LMTP
directly instead of via
.BR deliver .
.SH OPTIONS
.IP "-f sender"
specifies the fully qualified address of the message sender. This is
the same as the SMTP envelope sender.
.IP
If there is no
.I -f
argument,
.B deliver
looks for a sender address in the first line of the message, which
must be a "From " or "Return-Path:" field. If it isn't, the message
cannot be delivered.
.SH EXAMPLES
To deliver an entire berkeley mbox into the inbox of user nirmala@example.com:
.IP
formail -s deliver nirmala@example.com < mbox
.PP
To deliver each message in the MH folder +blah into the
inbox of user raj@example.net:
.IP
folder +blah
.br
seq all | xargs -n1 deliver raj@example.net
.SH DIAGNOSTICS
The normal exit status of
.B deliver
is 0. If the destination address is not accepted,
.B deliver
returns 1. If
.BR archiveopteryx (8)
does not accept the message body,
.B deliver
returns 2.
.SH BUGS
This program really needs a command-line option to set destination
mailbox.
.PP
Delivering multiple messages would also be good, for those big mailbox
migrations. In that case,
.B
deliver
should report which messages could be delivered and which could not.
.PP
The return codes may be wrong in a few cases. This man page probably
is right and the code wrong. Low priority.
.PP
There is no command-line option to set the configuration file.
.SH AUTHOR
The Archiveopteryx developers, info@oryx.com.
.SH VERSION
This man page covers Archiveopteryx version 1.11, released 2006-09-24,
http://www.archiveopteryx.org/1.11.html.
.SH SEE ALSO
.BR archiveopteryx (8),
.BR archiveopteryx.conf (5),
.BR logd (8),
.BR ocd (8),
.BR tlsproxy (8),
.BR oryx (7),
http://www.archiveopteryx.org
