.\" Copyright Oryx Mail Systems GmbH. Enquiries to info@oryx.com, please.
.TH installer 8 2007-01-15 www.oryx.com "Archiveopteryx Documentation"
.SH NAME
installer - Archiveopteryx installer.
.SH SYNOPSIS
.B $LIBDIR/installer
[
.I -n
] [
.I -q
] [
.I -v 
] ...
.SH DESCRIPTION
.nh
.PP
This program does the following:
.PP
1. Creates a Unix group named $AOXGROUP.
.PP
2. Creates a Unix user named $AOXUSER.
.PP
3. Creates a Postgres user named $AOXUSER.
.PP
4. Creates a Postgres user named $DBOWNER.
.PP
5. Creates a Postgres database named $DBNAME owned by $DBOWNER.
.PP
6. Loads the database schema and grants limited privileges to user $AOXUSER.
.PP
7. Generates an initial configuration file.
.PP
8. Adjusts ownership and permissions if necessary.
.PP
.B installer
should be run after
.I "jam install" 
when installing from source.
.SH OPTIONS
.IP -q
Suppresses all normal output.
.IP -v
Makes the output more verbose (may be repeated).
.IP -n
Causes the program to report what it would do, but not actually do
anything.
.IP "-g group"
Allows you to specify a Unix group other than the default of $AOXGROUP.
.IP "-u user"
Allows you to specify a Unix username other than the default of
$AOXUSER.
.IP "-p postgres"
Allows you to specify the name of the PostgreSQL superuser. The default
is to try $PGUSER (if set), postgres and pgsql in turn.
.IP "-a address"
Allows you to specify a different address for the Postgres server. The
default is $DBADDRESS.
.IP "-t port"
Allows you to specify a different port for the Postgres server. The
default is 5432. (This value is used only if the server address does
not refer to a Unix socket.)
.PP
The defaults come from
.IR Jamsettings .
.SH DIAGNOSTICS
The return code is zero if all goes well, and a non-zero in case of
errors. Disasters are logged via stderr.
.SH AUTHOR
The Archiveopteryx developers, info@oryx.com.
.SH VERSION
This man page covers Archiveopteryx version 1.15, released 2007-01-15,
http://www.archiveopteryx.org/1.15.html.
.SH SEE ALSO
.BR archiveopteryx (8),
.BR archiveopteryx.conf (5),
.BR logd (8),
.BR ocd (8),
.BR tlsproxy (8),
.BR oryx (7),
http://www.archiveopteryx.org
