.\" Copyright Oryx Mail Systems GmbH. Enquiries to info@oryx.com, please.
.TH installer 8 2006-09-09 www.oryx.com "Archiveopteryx Documentation"
.SH NAME
installer - Archiveopteryx installer.
.SH SYNOPSIS
.B $LIBDIR/installer
[
.I -n
] [
.I -q
] ...
.SH DESCRIPTION
.nh
.PP
This program does the following:
.IP 1. 3
Creates a Unix group named $AOXGROUP.
.IP 2. 3
Creates a Unix user named $AOXUSER.
.IP 3. 3
Creates a Postgres user named $AOXUSER.
.IP 4. 3
Creates a Postgres user named $DBOWNER.
.IP 5. 3
Creates a Postgres database named $DBNAME owned by $DBOWNER.
.IP 6. 3
Loads the database schema and grants limited privileges to user $AOXUSER.
.IP 7. 3
Generates an initial configuration file.
.IP 8. 3
Adjusts ownership and permissions if necessary.
.PP
.B installer
should be run after
.I "jam install" 
when installing from source.
.SH OPTIONS
.IP -q 4
Suppresses all normal output.
.IP -n 4
Causes the program to report what it would do, but not actually do
anything.
.IP "-g group" 4
Allows you to specify a Unix group other than the default of $AOXGROUP.
.IP "-u user" 4
Allows you to specify a Unix username other than the default of
$AOXUSER.
.IP "-p postgres" 4
Allows you to specify the name of the PostgreSQL superuser. The default
is to try $PGUSER (if set), postgres and pgsql in turn.
.IP "-a address" 4
Allows you to specify a different address for the Postgres server. The
default is $DBADDRESS.
.PP
The defaults come from
.IR Jamsettings .
.SH DIAGNOSTICS
The return code is zero if all goes well, and a non-zero in case of
errors. Disasters are logged via stderr.
.SH AUTHOR
The Archiveopteryx developers, info@oryx.com.
.SH VERSION
This man page covers Archiveopteryx version 1.10, released 2006-09-09,
http://www.archiveopteryx.org/1.10.html.
.SH SEE ALSO
.BR archiveopteryx (8),
.BR archiveopteryx.conf (5),
.BR logd (8),
.BR ocd (8),
.BR tlsproxy (8),
.BR oryx (7),
http://www.archiveopteryx.org
