.\" Copyright Oryx Mail Systems GmbH. Enquiries to info@oryx.com, please.
.TH imapd 8 2006-01-16 www.oryx.com "Archiveopteryx Documentation"
.SH NAME
logd - logging server for Archiveopteryx.
.SH SYNOPSIS
.B $BINDIR/logd [-f] [-c configfile]
.SH DESCRIPTION
.nh
.PP
The Archiveopteryx
.B logd
is an internal server which receives, buffers and filters log entries
from other parts of Archiveopteryx, so that useful messages are logged, while
noise is suppressed.
.PP
Archiveopteryx's log system uses transactions and four log levels:
.IR Disaster ,
.IR Error ,
.I Info
and
.IR Debug .
Each program in Archiveopteryx sends its log messages to
.BR logd ,
which stores them in RAM until a transaction ends.
.PP
If a message is logged with severity
.IR log-level
(usually set to
.IR Error )
or greater, it is immediately written to the log file. If the severity
is
.IR Error
or greater, all preceding messages of lower severity are also logged.
Otherwise, when a transaction ends, 
.I Debug
output is suppressed.
.PP
If a process dies unexpectedly, all of its open transactions are
logged as if a disaster happened.
.PP
If
.B logd
receives the SIGHUP signal, it closes and reopens its logfile.
.PP
After startup,
.B logd
changes root to the directory where
.I logfile
is located, and changes uid and gid to
.I jail-user
and
.IR  jail-group .
Therefore,
.I jail-user
must have the right to open
.IR logfile .
.SH OPTIONS
.IP "-c filename"
Read configuration variables from
.I filename
instead of from
.IR $CONFIGDIR/mailstore.conf .
.IP -f
Fork into background during startup.
.SH CONFIGURATION
.B logd
is configured using
.BR mailstore.conf (5).
.PP
.B logd
uses the following configuration variables:
.IR log-address ,
.IR log-port ,
.I logfile
(default $LOGFILE),
.I log-level
(default 
.IR info ),
.I jail-user
(default
.IR $ORYXUSER ),
.I jail-group
(default
.IR $ORYXGROUP ).
.SH DIAGNOSTICS
In case of error,
.B smtpd
exits with exit code 1, an error message on stderr and (usually more
detailed) information in the log file.
.SH FILES
$CONFIGDIR/mailstore.conf
.br
$BINDIR/logd
.SH AUTHOR
The Archiveopteryx developers, info@oryx.com.
.SH VERSION
This man page covers Archiveopteryx version 1.02, released 2006-01-16,
http://www.oryx.com/mailstore/1.02.html.
.SH SEE ALSO
.BR mailstore (7),
.BR mailstore.conf (5),
.br
.BR deliver (8),
.BR ms (8),
.br
.BR imapd (8),
.BR ocd (8),
.BR pop3d (8),
.BR smtpd (8),
.BR tlsproxy (8),
.br
.BR oryx (7),
http://www.oryx.com/mailstore/
