.\" Copyright Oryx Mail Systems GmbH. Enquiries to info@oryx.com, please.
.TH imapd 8 2004-07-20 www.oryx.com "Mailstore Documentation"
.SH NAME
logd - logging server for Oryx Mailstore.
.SH SYNOPSIS
.B $BINDIR/logd [-f] [-c configfile]
.SH DESCRIPTION
.nh
.PP
The Oryx Mailstore
.B logd
is an internal server which receives, buffers and filters log entries
from other parts of Mailstore, so that useful messages are logged, while
noise is suppressed.
.PP
Mailstore's log system uses transactions and four log levels:
.IR Disaster ,
.IR Error ,
.I Info
and
.IR Debug .
Each program in Mailstore sends its log messages to
.BR logd ,
which stores them in RAM until a transaction ends.
.PP
If a message is logged with severity
.IR loglevel
(usually set to
.IR Error )
or greater, it is immediately written to the log file. If the severity
is
.IR Error
or greater, all preceding messages of lower severity are also logged.
Otherwise, when a transaction ends, 
.I Debug
output is suppressed.
.PP
If a process dies unexpectedly, all of its open transactions are
logged as if a disaster happened.
.SH OPTIONS
Mostly, 
.B smtpd
is configured using
.BR mailstore.conf (5).
The only command-line options at present are:
.IP "-c filename"
Read configuration variables from
.I filename
instead of from
.IR $CONFIGDIR/mailstore.conf .
.IP -f
Fork into background during startup.
.SH DIAGNOSTICS
In case of error,
.B smtpd
exits with exit code 1, an error message on stderr and (usually more
detailed) information in the log file.
.SH FILES
$CONFIGDIR/mailstore.conf
.SH AUTHOR
The Oryx Mailstore developers, info@oryx.com.
.SH VERSION
This man page covers Oryx Mailstore version 0.90, released 2004-09-15,
http://www.oryx.com/mailstore/0.90.html.
.SH SEE ALSO
.BR mailstore (7),
.BR mailstore.conf (5),
.BR deliver (8),
.BR imapd (8),
.BR ocd (8),
.BR pop3d (8),
.BR smtpd (8),
.BR tlsproxy (8),
.BR oryx (7),
http://www.oryx.com/mailstore/
