.\" Copyright Oryx Mail Systems GmbH. Enquiries to info@oryx.com, please.
.TH mailstore.conf 5 2004-07-20 www.oryx.com "Mailstore Documentation"
.SH NAME
mailstore.conf - overall configuration for Oryx Mailstore.
.SH SYNOPSIS
.B $CONFIGDIR/mailstore.conf
.br
.SH DESCRIPTION
.nh
.PP
The
.I mailstore.conf
file contains all global configuration settings for Oryx Mailstore. It
is read by each server at startup. Syntax errors, unknown variables
etc. are logged via
.BR logd (8).
.SH "SECURITY NOTE"
Anyone who can read
.I mailstore.conf
can see the database password, and use this password to damage or
destroy the mail database.
.PP
By default, 
.I mailstore.conf
is readable only by root.
.SH SETTINGS
.PP
All settings share a common format:
.IP
name = value # comment
.PP
.SS "General Settings"
.IP hostname
Most of the servers need to know the fully-qualified hostname. The
default is computed at runtime and is normally acceptable.
.IP
Note that if the name is "localhost", there may be problems with
TLS. An IMAP/POP/SMTP client may refuse a server certificate for
"localhost" if it already has a different certificate for
"localhost". We strongly suggest using a different
.IR hostname .
.SS "Database Access"
.IP db
The type of database. The default,
.IR postgres ,
is currently the only supported value.
.IP db-address
The address of the database server. The default is
.IR $DBADDRESS .
You may use an IPv4 or IPv6 address, or the fully-qualified path to a
Unix socket.
.IP db-port
The port number of the database server. The default is
.IR 5432 .
.IP db-name
The name of the database to use. The default is
.IR $DBNAME .
.IP db-user
The user name Mailstore should use to connect to the database. The
default is
.IR $DBUSER .
.IP db-password
The password Mailstore should use to connect to the database. The
default is an empty password.
.IP
During installation, Mailstore sets up a randomly-chosen password by
default.
.IP db-max-handles
The maximum number of database handles that Mailstore may open. The
default is
.IR 4 .
.IP db-handle-interval
The minimum interval (in seconds) between the creation of new database
handles. The default is
.IR 120 .
.SS Logging
.IP log-address
The address of the log server. The default is
.IR 127.0.0.1 .
You may use an IPv4 or IPv6 address, or the fully-qualified path to a
Unix socket.
.IP log-port
The port number at which
.BR logd (8)
listens, and to which the other servers connect. The default is
.IR 2054 .
.IP logfile
is the name of the file to which
.BR logd (8)
writes log events. The file name must be absolute (start with '/'),
and the default is
.IR $LOGFILE .
.IP loglevel
can be
.IR debug ,
.IR error ,
or
.IR disaster ,
besides the default value of 
.IR info .
If a message is logged with this severity or above, the log server
immediately writes it to the log file. Messages with lower severity
are considered only when the transaction is commited, or when a message
is logged with a severity greater than
.IR error .
.SS Security
.IP security
is enabled by default, and should be enabled whenever Mailstore is
used in production. If security is disabled, the servers do not need
to be started as root, they keep stderr open, and they do not try to
lose privileges.
.IP
Turning security off has exactly one advantage: it simplifies
debugging.
.IP jail-directory
is the directory where the servers jail themselves,
.I $JAILDIR
by default. On startup, each server uses
.BR chroot (2)
into this directory, which should be empty.
.I jail-directory
should be empty and unreadable to
.IR jail-user .
.IP jail-user
is the user name under which the servers run, and is
.I nobody
by default. On startup, the servers change UID to this user. This user
should not have read or write access to the jail directory.
.IP jail-group
is the group name under which the servers run, and is
.I nogroup
by default. On startup, the servers change GID to this user.
.SS "Cluster Configuration"
.IP ocd-address
The address where
.BR ocd (8)
listens for connections from other Mailstore servers. The default is
.IR 127.0.0.1 .
You may use an IPv4 or IPv6 address, or the fully-qualified path to a
Unix socket.
.IP ocd-port
The port number at which
.BR ocd (8)
listens, and to which the other servers connect,
.I 2050
by default.
.IP ocadmin-address
The address where
.BR ocd (8)
listens for admin requests. The default is
.IR 127.0.0.1 .
You may use an IPv4 or IPv6 address, or the fully-qualified path to a
Unix socket.
.IP ocadmin-port
The port number at which
.BR ocd (8)
listens for admin requests.
.I 2050
by default.
.SS "User Authentication"
http://www.oryx.com/mailstore/sasl.html describes SASL and
authentication in more detail.
.IP allow-plaintext-passwords
controls whether the servers permit plaintext passwords, and how such
passwords are handled.
May be set to
.I always
(which is the default) or
.IR never .
(Future versions of Mailstore will offer more settings.)
.IP auth-digest-md5
controls whether the servers offer the digest-md5 SASL mechanism.
.I Enabled
by default.
.IP auth-cram-md5
controls whether the servers offer the cram-md5 SASL mechanism.
.I Enabled
by default.
.IP auth-plain
controls whether the servers offer the plain-text SASL
mechanism.
.I Enabled
by default.
.IP
Note that disabling auth-plain doesn't disable all plaintext
passwords, since SASL isn't always used. To disable plaintext
passwords, use the
.I allow-plaintext-passwords
variable above.
.IP auth-anonymous
controls whether the servers offer anonymous login. Disabled by
default.
.SS "Mail delivery"
.IP use-lmtp
controls whether the
.BR smtpd (8)
should accept mail via LMTP (RFC 2033). The default is
.IR enabled .
.IP lmtp-address
specifies the address where
.BR smtpd (8)
should listen for LMTP connections, and to which
.BR deliver (8)
should connect. The default is
.IR 127.0.0.1 .
You may use an IPv4 or IPv6 address, or the fully-qualified path to a
Unix socket.
.IP lmtp-port
specifies which port the
.BR smtpd (8)
should listen to, and which port
.BR deliver (8)
should connect to. The default is
.IR 2026 .
.IP use-smtp
controls whether the
.BR smtpd (8)
should accept mail via SMTP/ESMTP (RFC 2821/1869). SMTP is
.I disabled
by default.
.IP smtp-address
specifies the address where
.BR smtpd (8)
should listen for SMTP connections The default is an empty string,
which means all available IPv4 and IPv6 interfaces.
.IP smtp-port
specifies which port the
.BR smtpd (8)
should listen to. The default is
.I 25
(but since
.I use-smtp
is normally disabled,
.I smtp-port
is unused.)
.SS IMAP
.IP imap-address
is the address where the IMAP server listens for new connections. The
default, an empty string, means to listen on all available IPv4 and
IPv6 addresses.
.IP imap-port
is the port where the IMAP server accepts connections,
.I 143
by default.
.IP use-imaps
is enabled if the IMAP server should also accept SSL-wrapped
connections. The default is no.
.IP imaps-address
is the address where the IMAP server listens for new SSL-wrapped connections.
.IP imaps-port
is the port where the IMAP server accepts SSL-wrapped connections,
.I 993
by default.
.IP announce-draft-support
is enabled if the IMAP server should advertise support for
drafts. Oryx tracks the draft versions of several IMAP extensions
etc. Since these drafts are subject to change without notice, their
support is
.I disabled
by default, and can be enabled using this toggle.
.SS POP
.IP pop-address
is the address where the POP server listens for new connections. The
default, an empty string, means to listen on all available IPv4 and
IPv6 addresses.
.IP pop-port
is the port where the POP server accepts connections,
.I 110
by default.
.SS TLS
.IP use-tls
regulates whether Mailstore supports TLS at all. The default is
.IR enabled .
.IP tls-certificate
is the absolute file name of the TLS private key and signed certificate,
e.g.
.IR $CONFIGDIR/imap.p15 .
If
.I tls-certificate
is not specified, tlsproxy generates a private key and a self-signed
certificate at runtime and stores both in
.IR $CONFIGDIR/automatic-key.p15 .
.IP tlsproxy-address
is the address where the tlsproxy listens for new connections. The
default is
.IR 127.0.0.1 .
.IP tlsproxy-port
is the port where the tlsproxy accepts connections,
.I 2061
by default.
.SH SYNTAX
.PP
The name is case insensitive, as shown:
.IP
hostname = test1.example.com
.br
HOSTNAME = mailserver.example.org
.PP
The value is case insensitive wherever possible. (Exceptions
include logfile, db-user and db-pass.)
.PP
There are three datatypes: Strings, numbers and toggles.
.PP
Strings may be written as a single unquoted word or quoted with either
single or double quotes, as shown in these three examples:
.IP
dbpass = single.word
.br
dbpass = "rock'n'roll" # a 12-character password
.br
dbpass = 'two words, quoted' # a 17-character one
.PP
Only single-line strings can be used. Single-word strings may contain
the characters a-z, A-Z, 0-9, dot, hyphen and slash.
.PP
Numbers are integers not smaller than 0 and not larger than 2147483647
(ie. 31-bit unsigned integers).
.PP
Toggles are written as a single word.
.IR Yes ,
.IR true ,
.IR on ,
.I 1
and
.I enabled
all
mean that the toggle is enabled, while
.IR no ,
.IR false ,
.IR off ,
.I 0
and
.I disabled
unsurprisingly mean disabled. Toggles are case-insensitive.
.IP
use-lmtp = yes
.br
crash-and-delete-all-the-mail = off
.PP
Spaces are allowed at the start of the line, before and after '=', and
after the value. Comments extend from '#' to the end of the line.
.IP
# this is a comment
.br
hostname=stuff.nonsense.example.com # also a comment
.br
 logfile    =   /dev/null# and this is a comment
.br

.br
# empty lines are ignored
.SH AUTHOR
The Oryx Mailstore developers, info@oryx.com.
.SH VERSION
This man page covers Oryx Mailstore version 0.93, released 2005-04-18,
http://www.oryx.com/mailstore/0.93.html.
.SH SEE ALSO
.BR mailstore (7),
.BR deliver (8),
.BR imapd (8),
.BR logd (8),
.BR ocd (8),
.BR pop3d (8),
.BR smtpd (8),
.BR tlsproxy (8),
.BR oryx (7),
http://www.oryx.com/mailstore/
