.\" Copyright Oryx Mail Systems GmbH. Enquiries to info@oryx.com, please.
.TH imapd 8 2004-07-20 www.oryx.com "Mailstore Documentation"
.SH NAME
ocd - cluster coordination server for Oryx Mailstore.
.SH SYNOPSIS
.B $BINDIR/ocd [-f] [-c configfile]
.SH DESCRIPTION
.nh
.PP
.B ocd
is responsible for message passing, cache updates and various other
houskeeping tasks for Oryx Mailstore. It must always be running while
Mailstore runs, but should never be visible to the user.
.SH OPTIONS
Mostly, 
.B ocd
is configured using
.BR mailstore.conf (5).
The only command-line options at present are:
.IP "-c filename"
Read configuration variables from
.I filename
instead of from
.IR $CONFIGDIR/mailstore.conf .
.IP -f
Fork into background during startup.
.SH DIAGNOSTICS
In case of error,
.B ocd
exits with exit code 1, an error message on stderr and (usually more
detailed) information in the log file.
.SH BUGS
At some future date,
.B ocd
will offer a management console. It doesn't yet, though.
.SH AUTHOR
The Oryx Mailstore developers, info@oryx.com.
.SH VERSION
This man page covers Oryx Mailstore version 0.94, released 2005-05-16,
http://www.oryx.com/mailstore/0.94.html.
.SH SEE ALSO
.BR mailstore (7),
.BR mailstore.conf (5),
.BR deliver (8),
.BR imapd (8),
.BR logd (8),
.BR pop3d (8),
.BR smtpd (8),
.BR tlsproxy (8),
.BR oryx (7),
http://www.oryx.com/mailstore/
