.\" Copyright Oryx Mail Systems GmbH. Enquiries to info@oryx.com, please.
.TH smtpd 8 2004-07-20 www.oryx.com "Mailstore Documentation"
.SH NAME
smtpd - SMTP and LMTP server for Oryx Mailstore.
.SH SYNOPSIS
.B $BINDIR/smtpd [-f] [-c configfile]
.SH DESCRIPTION
.nh
.PP
This
.B smtpd
is the SMTP and LMTP server from Oryx Mailstore, a fast, high-capacity
mail server which uses a database for mail storage.
.PP
.B smtpd
only accepts mail for local delivery; it will not relay or forward mail.
.SH OPTIONS
Mostly, 
.B smtpd
is configured using
.BR mailstore.conf (5).
The only command-line options at present are:
.IP "-c filename"
Read configuration variables from
.I filename
instead of from
.IR $CONFIGDIR/mailstore.conf .
.IP -f
Fork into background during startup.
.SH DIAGNOSTICS
In case of error,
.B smtpd
exits with exit code 1, an error message on stderr and (usually more
detailed) information in the log file.
.SH AUTHOR
The Oryx Mailstore developers, info@oryx.com.
.SH VERSION
This man page covers Oryx Mailstore version 0.94, released 2005-05-16,
http://www.oryx.com/mailstore/0.94.html.
.SH SEE ALSO
.BR mailstore (7),
.BR mailstore.conf (5),
.BR deliver (8),
.BR imapd (8),
.BR logd (8),
.BR ocd (8),
.BR pop3d (8),
.BR tlsproxy (8),
.BR oryx (7),
http://www.oryx.com/mailstore/
