.\" Copyright Oryx Mail Systems GmbH. Enquiries to info@oryx.com, please.
.TH tlsproxy 8 2005-09-19 www.oryx.com "Mailstore Documentation"
.SH NAME
tlsproxy - TLS/SSL helper for Oryx Mailstore.
.SH SYNOPSIS
.B $BINDIR/tlsproxy [-f] [-c configfile]
.SH DESCRIPTION
.nh
.PP
The Oryx Mailstore
.B tlsproxy
is a separate process which performs TLS and SSLv3 processing on behalf of
.BR imapd (8),
.BR pop3d (8)
and
.BR smtpd (8).
TLS processing is kept separate from these other servers for
architectural reasons:
.PP
TLS occasionally causes processing delays, for example while
regenerating keys. Since most of Mailstore is event-driven, these
delays would block other users.
.PP
Further, there is a lot of code in cryptlib, which we prefer not to
link into all of our servers.
.PP
.B tlsproxy
should always be running when Mailstore is in use, but you should
never need to interact with it directly.
.SH OPTIONS
Mostly, 
.B tlsproxy
is configured using
.BR mailstore.conf (5).
The only command-line options at present are:
.IP "-c filename"
Read configuration variables from
.I filename
instead of from
.IR $CONFIGDIR/mailstore.conf .
.IP -f
Fork into background during startup.
.SH DIAGNOSTICS
In case of error,
.B tlsproxy
exits with exit code 1, an error message on stderr and (usually more
detailed) information in the log file.
.SH "CERTIFICATE HANDLING"
.B Tlsproxy
can use a proper certificate signed by a CA, as usual. If you
do not have one,
.B tlsproxy
will generate a self-signed certificate at runtime. No clients trust
this certificate, but we think it's better to have a self-signed
certificate than to not use TLS.
.PP
Oryx strongly recommends getting a proper signed certificate. Using
the dynamically generated certificate preserves some of the advantages
of TLS, but far from all.
.SH FILES
.IP $LIBDIR/automatic-key.p15
is used to store the automatically generated key and certificate.
.SH AUTHOR
The Oryx Mailstore developers, info@oryx.com.
.SH VERSION
This man page covers Oryx Mailstore version 0.98, released 2005-09-19,
http://www.oryx.com/mailstore/0.98.html.
.SH SEE ALSO
.BR mailstore (7),
.BR mailstore.conf (5),
.BR deliver (8),
.BR imapd (8),
.BR logd (8),
.BR ocd (8),
.BR pop3d (8),
.BR smtpd (8),
.BR oryx (7),
http://www.oryx.com/mailstore/
