#!/bin/sh

#-----------------------------------------------------------------------
# Cryptlib for MVS
# 
# Developed on OS/390 2.10.
#
# Copy files from the 'test' directory to the MVS data sets allocated 
# with ussalloc.  This must be executed from the 'test' directory.
#-----------------------------------------------------------------------

# The file extensions to copy from the 'test' directory.
BINEXTS="p15 p12 der pgp gpg pkr skr p7s"

# The middle-level qualifier of the test data sets.
MLQ=CRYPTLIB


for i in $BINEXTS; do
    for j in `ls *.$i`; do
        mbr=`echo $j | awk -F '.' '{print $1}' | tr -d '_'`
        cp -BA $j "//$MLQ.CLB$i($mbr)"
    done
done

cp -BA test.h "//$MLQ.CLBCMP"

