// Copyright 2009 The Archiveopteryx Developers <info@aox.org>

#include "sort.h"

#include "user.h"
#include "field.h"
#include "codec.h"
#include "postgres.h"
#include "mailbox.h"
#include "imapparser.h"
#include "imapsession.h"


class SortData
    : public Garbage
{
public:
    SortData(): Garbage(), s( 0 ), q( 0 ), u( false ) {}

    enum SortCriterionType {
        Arrival,
        Cc,
        Date,
        DisplayFrom,
        DisplayTo,
        From,
        Size,
        Subject,
        To,
        Unknown
    };

    class SortCriterion
        : public Garbage {
    public:
        SortCriterion()
            : t( Unknown ), reverse( false ) {}

        SortCriterionType t;
        bool reverse;
    };

    List<SortCriterion> c;

    Selector * s;
    Query * q;
    bool u;

    bool usingCriterionType( SortCriterionType );

    EString key( SortCriterionType );
    EString addressKey( uint, bool );
    EString collation();
};


/*! \class Sort sort.h

    The Sort class implements the IMAP SORT extension, which is
    defined in RFC 5256.

    This class subclasses Search in order to take advantage of its
    parser, and operates quite nastily on the Query generated by
    Selector.
*/



/*! Constructs an empty Sort handler. If \a u is true, the SORT
    response will use UIDs, if it's false it will use MSNs.
*/

Sort::Sort( bool u )
    : Search( u ), d( new SortData )
{
    d->u = u;
}


void Sort::parse()
{
    // sort-criteria
    space();
    require( "(" );
    bool x = true;
    while ( x ) {
        uint m = parser()->mark();
        if ( !d->c.isEmpty() )
            space();
        SortData::SortCriterion * c = new SortData::SortCriterion;
        EString s = parser()->dotLetters( 2, 11 ).lower();
        if ( s == "reverse" ) {
            space();
            s = parser()->dotLetters( 2, 11 ).lower();
            c->reverse = true;
        }
        if ( s == "arrival" ) {
            c->t = SortData::Arrival;
        }
        else if ( s == "cc" ) {
            c->t = SortData::Cc;
        }
        else if ( s == "date" ) {
            c->t = SortData::Date;
        }
        else if ( s == "displayfrom" ) {
            c->t = SortData::DisplayFrom;
        }
        else if ( s == "displayto" ) {
            c->t = SortData::DisplayTo;
        }
        else if ( s == "from" ) {
            c->t = SortData::From;
        }
        else if ( s == "size" ) {
            c->t = SortData::Size;
        }
        else if ( s == "subject" ) {
            c->t = SortData::Subject;
        }
        else if ( s == "to" ) {
            c->t = SortData::To;
        }
        if ( ok() && c->t != SortData::Unknown ) {
            if ( !d->usingCriterionType( c->t ) )
                d->c.append( c );
        }
        else {
            parser()->restore( m );
            x = false;
        }
    }
    require( ")" );

    space();

    // Optional charset; there is an erratum in 6855 that doesn't
    // specify syntax. I bet this isn't quite what Barry had in mind.
    parser()->mark();
    EString charset = astring();
    if ( Codec::byName( charset ) ) {
        setCharset( charset );
        space();
    } else {
        parser()->restore();
    }

    // search-criteria
    d->s = new Selector;
    d->s->add( parseKey() );
    while ( ok() && !parser()->atEnd() ) {
        space();
        d->s->add( parseKey() );
    }
    end();
}


/*! This reimplementation hides Search::execute() entirely.

    Selector's query becomes a subquery, so the sort keys can use
    their own table names without colliding with Selector's.
*/

void Sort::execute()
{
    if ( state() != Executing )
        return;

    if ( !d->q ) {
        d->s->simplify();
        d->q = d->s->query( imap()->user(), session()->mailbox(),
                            session(), this, false );
        EString t = "select s.uid from (" + d->q->string() + ") s";
        if ( d->usingCriterionType( SortData::Arrival ) ||
             d->usingCriterionType( SortData::Size ) )
            t.append( " join messages m on (m.id=s.message)" );
        t.append( " order by " );
        List<SortData::SortCriterion>::Iterator c( d->c );
        while ( c ) {
            t.append( d->key( c->t ) );
            if ( c->reverse )
                t.append( " desc" );
            t.append( ", " );
            ++c;
        }
        t.append( "s.uid" );
        d->q->setString( t );
        d->q->execute();
    }

    if ( !d->q->done() )
        return;

    List<uint> * result = new List<uint>;
    Row * r;
    while ( (r=d->q->nextRow()) != 0 ) {
        uint * tmp = (uint *)Allocator::alloc( sizeof(uint), 0 );
        *tmp = r->getInt( "uid" );
        result->append( tmp );
    }
    waitFor( new ImapSortResponse( session(), result, d->u ) );
    finish();
}


/*! Returns an SQL expression for the sort key of type \a t, for use
    in Sort::execute()'s order by clause.

    The string keys are lower-cased and compared using collation().
    RFC 5256 says i;ascii-casemap, but I think users prefer a natural
    sort order to an RFC-compliant one. Each key is a subselect with
    limit 1, so that a message with two From fields (or similar)
    still yields just one row.
*/

EString SortData::key( SortCriterionType t )
{
    switch ( t ) {
    case Arrival:
        return "m.idate";
    case Size:
        return "m.rfc822size";
    case Date:
        return "(select value from date_fields"
            " where message=s.message limit 1)";
    case Subject:
        return "(select lower(value" + collation() + ")"
            " from header_fields where message=s.message and part=''"
            " and field=" + fn( HeaderField::Subject ) +
            " order by position limit 1)" + collation();
    case Cc:
        return addressKey( HeaderField::Cc, false );
    case From:
        return addressKey( HeaderField::From, false );
    case To:
        return addressKey( HeaderField::To, false );
    case DisplayFrom:
        return addressKey( HeaderField::From, true );
    case DisplayTo:
        return addressKey( HeaderField::To, true );
    case Unknown:
        break;
    }
    return "s.uid";
}


/*! Returns an SQL expression for the first address in the field \a
    f. If \a display is false, the expression is the addr-mailbox
    (RFC 5256), if true, the display name or address (RFC 5957).
*/

EString SortData::addressKey( uint f, bool display )
{
    EString v = "a.localpart::text";
    if ( display )
        v = "case when coalesce(a.name,'')='' "
            "then a.localpart||'@'||a.domain "
            "else a.name end";
    return "(select lower((" + v + ")" + collation() + ")"
        " from address_fields af"
        " join addresses a on (af.address=a.id)"
        " where af.message=s.message and af.part=''"
        " and af.field=" + fn( f ) + " and af.number=0"
        " order by af.position limit 1)" + collation();
}


/*! Returns a collate clause for ICU's root collation, or an empty
    string on servers older than 10, which have no ICU. Those sort
    using the database's default collation, which is usually a libc
    locale and may be just C.
*/

EString SortData::collation()
{
    if ( Postgres::version() < 100000 )
        return "";
    return " collate \"und-x-icu\"";
}


bool SortData::usingCriterionType( SortCriterionType t )
{
    List<SortCriterion>::Iterator i( c );
    while ( i && i->t != t )
        ++i;
    if ( i )
        return true;
    return false;
}


/*! \class ImapSortResponse sort.h

    The ImapSortResponse models the SORT response, and has to make
    sure old MSNs aren't accidentally included.
*/



/*! Constructs a SORT response which will return \a result within \a
    session, using UIDs if \a uid is true and MSNs if \a uid is false.
*/

ImapSortResponse::ImapSortResponse( ImapSession * session,
                                    List<uint> * result, bool uid )
    : ImapResponse( session ),r( result ), u( uid )
{
}


EString ImapSortResponse::text() const
{
    Session * s = session();
    EString result;
    result.reserve( r->count() * 10 );
    result.append( "SORT" );
    List<uint>::Iterator i( r );
    while ( i ) {
        uint x = *i;
        ++i;
        if ( !u )
            x = s->msn( x );
        if ( x ) {
            result.append( " " );
            result.appendNumber( x );
        }
    }
    return result;
}
