#!/bin/sh
#
# No copyright is claimed for this file.
#
# See http://www.archiveopteryx.org/ for more about Archiveopteryx.

# Note: BINDIR is evaluated at build time.
cd $BINDIR

case "$1" in
    start)
        echo -n "Starting Archiveopteryx: "
        ./aox start
        echo "done."
        ;;
    stop)
        echo -n "Stopping Archiveopteryx: "
        ./aox stop
        echo "done."
        ;;
    restart)
        echo -n "Restarting Archiveopteryx: "
        ./aox restart
        echo "done."
        ;;
    status)
        ./aox show status
        ;;
    *)
        echo "Usage: archiveopteryx {start|stop|restart|status}"
        exit 1
        ;;
esac

exit 0
