#!/bin/sh
#
# No copyright is claimed for this file.
#
# See http://www.archiveopteryx.org/ for more about Archiveopteryx.

# Note: Jamsettings variables are evaluated at build time.
cd $BINDIR

case "$1" in
    start)
        echo -n "Starting Archiveopteryx: "
        ./ms start
        echo "done."
        ;;
    stop)
        echo -n "Stopping Archiveopteryx: "
        ./ms stop
        echo "done."
        ;;
    restart)
        echo -n "Restarting Archiveopteryx: "
        ./ms restart
        echo "done."
        ;;
    *)
        echo "Usage: archiveopteryx {start|stop|restart}"
        exit 1
        ;;
esac

exit 0
