#!/bin/sh
#
# This script uses the Jamsettings to set up a database and write a stub
# configuration file for Mailstore to use. (We assume that we're running
# as root.)

if [ `id -u` != 0 ]; then
    echo Please run the install script as root.
    exit 1
fi

TELL=no
if [ "$1" = "-n" ]; then
    TELL=yes;
    echo "Reporting what needs to be done."
fi

# Pull in the compile-time configuration
. $LIBDIR/.config.sh

CONFIG=$CONFIGDIR/mailstore.conf

# If we're upgrading from an older version, we probably don't want to
# overwrite anything. That mailstore.conf may contain a custom
# db-user, etc.
if [ -f $CONFIG -a $TELL = no ]; then
    echo $CONFIG already exists -- exiting without changes.
    echo " - not creating unix user" $UNIXUSER " and group " $ORYXGROUP
    echo " - not creating PostgreSQL user" $DBUSER
    echo " - not creating PostgreSQL database" $DBNAME
    echo " - not creating stub configuration file" $CONFIG
    exit 0
fi

# Is there an oryx user and group?
GROUPS=`id $ORYXUSER 2>/dev/null` || NOORYXUSER=1
# (There does not seem to be a properly portable way to identify a group)
grep '^'$ORYXGROUP':' /etc/group >/dev/null 2>/dev/null || NOORYXGROUP=1


# I am so very happy that we don't intend to support many platforms.
# platform conditionals are painful, and the ones below appear
# inescapable.

if [ $NOORYXGROUP ]; then
    if [ $TELL = yes ]; then
	echo Make a group called $ORYXGROUP, e.g. with
	echo "    groupadd $ORYXGROUP";
    elif [ -x /usr/sbin/groupadd ]; then
	/usr/sbin/groupadd $ORYXGROUP
    else
	echo Need to make a unix group called $ORYXGROUP, but do not know how
	echo to. Please make one by hand, then rerun the install script.
	exit 1
    fi
fi

if [ $NOORYXUSER = 1 ]; then
    if [ $TELL = yes ]; then
	echo Make a user called $ORYXUSER, e.g. with
    	echo "    useradd -r -g $ORYXGROUP $ORYXUSER"
	echo The new user does not need a valid login shell or password.
    elif [ -f /etc/SuSE-release -a -x /usr/sbin/useradd ]; then
	useradd -r -g $ORYXGROUP $ORYXUSER
    elif [ -x /usr/sbin/useradd ]; then
	# other linux
	useradd -g $ORYXGROUP $ORYXUSER
    else
	echo Need to make a unix user called $ORYXGROUP, but do not know how
	echo to. Please make one by hand, then rerun the install script.
	echo The new user does not need a valid login shell or password.
	exit 1
    fi
fi


# Find psql and pg_ctl
if [ "$PGBIN" = "" ]; then
    PSQL=psql
    PGCTL=pg_ctl
else
    PSQL=$PGBIN/psql
    PGCTL=$PGBIN/pg_ctl
fi

if [ -x /sbin/md5 ]; then
    MD5=/sbin/md5;
elif [ -x /usr/bin/md5 ]; then
    MD5=/usr/bin/md5;
elif [ -x /usr/bin/md5sum ]; then
    MD5=/usr/bin/md5sum
else
    echo "Cannot find md5 or md5sum"
    exit 1;
fi

# a hack to notify people of debian's change
if [ "$DBADDRESS" = /tmp/.s.PGSQL.5432 -a -f /etc/debian_version -a -S /var/run/postgresql/.s.PGSQL.5432 ]; then
    echo "DBADDRESS is $DBADDRESS, which may be wrong."
    echo "On Debian, maybe it should be /var/run/postgresql/.s.PGSQL.5432"
fi

## Set up the database.
#
# Do we need to create the oryx user?

EXISTS="select usename from pg_catalog.pg_user where usename = '$DBUSER'"
EXISTS=$(su - $PGUSER -c "$PSQL -d template1 -Atqc \"$EXISTS\"")
if [ ! $EXISTS ]; then
    if [ ! $DBPASS ]; then
        DBPASS=$(dd if=/dev/urandom bs=8 count=1 2>/dev/null|${MD5}|cut -b-32)
    fi
    CREATE="create user $DBUSER with encrypted password '$DBPASS'"
    if [ $TELL = no ]; then
        echo "Creating PostgreSQL user" $DBNAME
        su - $PGUSER -c "$PSQL -d template1 -qc \"$CREATE\"" || exit
    else
        echo
        echo "Need to create PostgreSQL user $DBNAME. As $PGUSER, run this:"
	echo "    $PSQL -d template1 -qc \"$CREATE\""
    fi
elif [ $TELL = yes ]; then
    echo "PostgreSQL user $DBUSER already exists, no action necessary."
    if [ ! $DBPASS ]; then
        DBPASS="(PostgreSQL password for $DBUSER here)"
    fi
fi


# Do we need to create the mailstore database?
#
# Unfortunate problem: if the database exists, but is not owned by the
# user we either found or created above... but in that case, what can
# we do anyway?

EXISTS="select datname from pg_catalog.pg_database where datname = '$DBNAME'"
EXISTS=$(su - $PGUSER -c "$PSQL -d template1 -Atqc \"$EXISTS\"")
if [ ! $EXISTS ]; then
    CREATE="create database $DBNAME with owner $DBUSER encoding 'UNICODE'"
    if [ $TELL = no ]; then
        echo "Creating PostgreSQL database" $DBNAME
        su - $PGUSER -c "$PSQL -d template1 -qc \"$CREATE\"" || exit
    else
        echo
        echo "Need to create PostgreSQL database $DBNAME. As $PGUSER, run this:"
        echo "    $PSQL -d template1 -qc \"$CREATE\""
        NEEDSCHEMA=yes
    fi
elif [ $TELL = yes ]; then
    echo "PostgreSQL database $DBNAME already exists, no action necessary."
fi


# Feed the schema to the database if necessary.

if [ $TELL = no ]; then
    EXISTS="select relname from pg_catalog.pg_class where relname='mailstore'"
    EXISTS=$(su - $PGUSER -c "$PSQL -d $DBNAME -Atqc \"$EXISTS\"")
    if [ ! $EXISTS ]; then
        echo "Loading Mailstore schema"
        cat <<PSQL | su - $PGUSER -c "$PSQL -q -d $DBNAME -f -" || exit
\set ON_ERROR_STOP
SET SESSION AUTHORIZATION $DBUSER;
SET client_min_messages TO 'ERROR';
\i $LIBDIR/schema.pg
\i $LIBDIR/field-names
\i $LIBDIR/flag-names
PSQL
    fi
elif [ -n "$NEEDSCHEMA" ]; then
    echo
    echo "Need to load Mailstore schema. As $PGUSER, run this:"
    echo "    $PSQL -q -d $DBNAME"
    echo "    \\set ON_ERROR_STOP"
    echo "    SET SESSION AUTHORIZATION $DBUSER;"
    echo "    SET client_min_messages TO 'ERROR';"
    echo "    \\i $LIBDIR/schema.pg"
    echo "    \\i $LIBDIR/field-names"
    echo "    \\i $LIBDIR/flag-names"
elif [ $TELL = yes ]; then
    echo "Mailstore schema already exists, no action necessary."
fi


# Write a stub configuration file.

if [ -f $CONFIG ]; then
    echo "$CONFIG already exits, no action necessary"
    exit 0
elif [ $TELL = no ]; then
    echo "Creating stub configuration $CONFIG"
    touch $CONFIG
    chmod 0600 $CONFIG
    chown $ORYXUSER $CONFIG
    chgrp $ORYXGROUP $CONFIG
    exec > $CONFIG
cat <<HEADER
# Mailstore configuration. For more about this, see the mailstore.conf
# man page.

# Specify the hostname if mailstore gets it wrong. We suggest not
# using the name "localhost".
# hostname = fully.qualified.hostname

# This database was initialized during Mailstore $VERSION installation.
# Date: `date`

HEADER
else
    echo
    echo "Create $CONFIG with mode 600:"
    echo "    touch $CONFIG"
    echo "    chmod 0600 $CONFIG"
    echo "    chown $ORYXUSER $CONFIG"
    echo "    chgrp $ORYXGROUP $CONFIG"
    echo
    echo "Insert e.g. the following into $CONFIG:"
fi
cat <<CONFIG
logfile-mode = 400
db-address  = $DBADDRESS
db-name     = $DBNAME
db-user     = $DBUSER
# Security Note: Anyone who can read the password in this file can do
# anything to your mail database, even delete all the mail.
db-password = ${DBPASS:-'""'}
CONFIG
