#!/bin/sh
#
# No copyright is claimed for this file.
#
# See http://www.oryx.com/mailstore/ for more about Oryx Mailstore, or
# write to info@oryx.com.

# Note: Jamsettings variables are evaluated at build time.
cd $SBINDIR

SERVERS="logd ocd tlsproxy imapd smtpd httpd"

REVERSE=""
for a in $SERVERS ; do REVERSE="$a $REVERSE"; done

for a in $SERVERS ; do
    test -x ${a} || exit 0
done

startserver() {
    ./$1 -f && echo -n " $1" || exit 0
}

stopserver() {
    P=$PIDFILEDIR/$1.pid
    if [ -f $P ]; then
        kill `cat $P` 2>/dev/null
        rm $P
        echo -n " $1";
    fi
}

check() {
    RUNNING=""
    for a in $SERVERS ; do
        test -f $PIDFILEDIR/${a}.pid && RUNNING="$RUNNING $a"
    done
    if [ "$RUNNING" != "" ]; then
        echo "The following servers are running already:"
	echo "    $RUNNING"
        echo "Please kill them (or delete $PIDFILEDIR/*.pid) first."
        exit 1
    fi
}


start() {
    echo -n "Starting Oryx Mailstore:"
    for a in $SERVERS ; do
        startserver $a
    done
    echo "."
}

stop() {
    echo -n "Stopping Oryx Mailstore:"
    for a in $REVERSE ; do
        stopserver $a
    done
    echo "."
}

case "$1" in
    start)
        check
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: mailstore {start|stop|restart}"
        exit 1
        ;;
esac

exit 0
