#!/bin/sh
#
# No copyright is claimed for this file.
#
# See http://www.oryx.com/mailstore/ for more about Oryx Mailstore, or
# write to info@oryx.com.

# Note: Jamsettings variables are evaluated at build time.
cd $BINDIR

SERVERS="logd ocd tlsproxy imapd smtpd"

REVERSE=`echo $SERVERS | fmt -1 | rev | fmt -666 | rev`

for a in $SERVERS ; do
    test -x ${a} || exit 0
done

start() {
    echo -n "Starting Oryx Mailstore:"
    for a in $SERVERS ; do
        ./${a} -f && echo -n " $a" || exit 0
    done
    echo "."
}

stop() {
    echo -n "Stopping Oryx Mailstore:"
    for a in $REVERSE ; do
	P=$PIDFILEDIR/${a}.pid
	if [ -f $P ]; then
	    kill `cat $P` 2>/dev/null
	    rm $P
	    echo -n " $a";
	else
	    # hm. this is dubious.
	    killall $a 2>/dev/null
	fi
    done
    echo "."
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: mailstore {start|stop|restart}"
        exit 1
        ;;
esac

exit 0
